<?php
/**
 * Created by PhpStorm.
 * User: KF
 * Date: 2018/9/23
 * Time: 16:37
 */
namespace app;

use think\App;
use think\Controller;
use think\Env;

class Base extends Controller
{
    /**
     * 错误信息
     * @var null
     */
    public $error=null;

    /**
     * 错误代码
     * @var int
     */
    public $errorCode = 1;

    public $viewPath=null;

    public function __construct(App $app = null)
    {
        parent::__construct($app);
    }

    /**
     * 初始化操作
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        //当前url
        define('CURRENT_URL',url(request()->module().'/'.strtolower(request()->controller()).'/'.request()->action()));
        if(!request()->isAjax()){
            //模版初始化
            $this->tempIni('default');
        }

    }

    /**
     * 模版初始化
     * @param $themName
     */
    private function tempIni($themName)
    {
        $themeIniName='THEME_INI';
        $theme=cookie($themeIniName);
        if ($theme!==null){
            $themName=$theme;
        }
        $themePath=  TEMPLATE_PATH.request()->module().'/';
        if(request()->isMobile()){
            $themePath=$themePath.'mobile/';
        }else{
            $themePath=$themePath.'pc/';
        };
        $themePath=$themePath.$themName.'/';
        $viewPath=$themePath.'page/';
        $relativeViewPath='.'.$viewPath;
        //如果模板不存在则使用默认的模板
        if (!file_exists($relativeViewPath)){
            $defaultTheme='default';
            if (!file_exists($defaultTheme)){
                die('无可用视图模板');
            }
            cookie($themeIniName,null);
            $this->tempIni($defaultTheme);
        }else{
            $assets=$themePath.'static/assets/'.strtolower(request()->controller()).'/'.strtolower(request()->action()).'/';
            //设置模板根目录
            $this->view->config('view_path', $relativeViewPath);
            //变量
            $this->view->assign([
                'static' =>  [
                    'common'  =>  $themePath.'static/common/',
                    'assets'  =>  $assets,
                ],
                'assets' =>  [
                    'js'      =>  $assets.'js/default.js'.'?t='.time(),//新增防缓存
                    'css'     =>  $assets.'css/default.css'.'?t='.time(),//新增防缓存
                    'img'     =>  $assets.'img/',
                ]
            ]);
            /*config('template.tpl_replace_string',[
                //资源文件路径
                '__STATIC__' => $themePath.'static/',
                //私有资源路径
                '__ASSETS__' => $assets,
                '__JS__' => $assets.'js/default.js',
                '__CSS__' => $assets.'css/default.css',
                '__IMG__' => $assets.'img/',

            ]);*/

            unset($themePath);
            cookie($themeIniName,$themName);
        }
    }



    /**
     * 返回错误信息
     * @return null|string
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * 设置错误信息
     * @param $code //错误代码
     * @param $msg  //错误说明
     */
    public function setError($code,$msg){
        $this->errorCode = $code;
        $this->error = $msg;
    }
}