<?php
/**
 * Created by PhpStorm.
 * User: KF
 * Date: 2018/11/6
 * Time: 11:04
 */

namespace app\admin\controller;


class Common extends \app\Base
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}