<?php
/**
 * Created by PhpStorm.
 * User: KF
 * Date: 2019/6/25
 * Time: 18:14
 */

namespace app\home;


use think\Controller;

class Common extends Controller
{

    /**
     * 错误信息
     * @var null
     */
    public $error=null;

    /**
     * 错误代码
     * @var int
     */
    public $errorCode = 1;

    /**
     * 配置session
     * @var string
     */
    public $configSession = "site_config";

    /**
     * 站点配置
     * @var null
     */
    public $siteConfig = null;

    /**
     * 初始化操作
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        //获取站点配置，如果配置没有缓存则从数据库获取
        if (!$config = session($this->configSession . '/')){
            $config = db('config')->where(["status"=>1])->find();
            if(!$config){
                die("未获取到站点配置");
            }
            session('site_config',$config);
        }
        $this->siteConfig = $config;

        //当前url
        define('CURRENT_URL',url(request()->module().'/'.strtolower(request()->controller()).'/'.request()->action()));
        if(!request()->isAjax()){
            //模版初始化
            $this->tempIni();
        }

    }

    /**
     * 模版初始化
     */
    private function tempIni(){
        $defaultTheme = 'default';
        $themePath=  TEMPLATE_PATH.request()->module() . "/";
        if(request()->isMobile()){
            $themName = $this->siteConfig['site_mobile_theme'] ?? $defaultTheme;
            $pt = "mobile";
        }else{
            $themName = $this->siteConfig['site_pc_theme'] ?? $defaultTheme;
            $pt = "pc";
        };
        $themePath2 = $themePath . $pt . "/" . $themName .'/';
        $relativeViewPath = '.' . $themePath2 . 'page/';

        //如果模板不存在则使用默认的模板
        if (!file_exists($relativeViewPath)){
            $relativeViewPath = '.' . $themePath . $pt . "/" . $defaultTheme . '/page/';
            if (!file_exists($relativeViewPath)){
                die('无可用视图模板');
            }
        }
        $assets=$themePath2  . 'static/assets/'.strtolower(request()->controller()).'/'.strtolower(request()->action()).'/';
        //设置模板根目录
        $this->view->config('view_path', $relativeViewPath);
        //变量
        $this->view->assign([
            'static' =>  [
                'common'  =>  $themePath2 . 'static/common/',
                'assets'  =>  $assets,
            ],
            'assets' =>  [
                'js'      =>  $assets.'js/default.js'.'?t='.time(),//新增防缓存
                'css'     =>  $assets.'css/default.css'.'?t='.time(),//新增防缓存
                'img'     =>  $assets.'img/',
            ]
        ]);
        unset($themePath);
    }

    /**
     * 返回错误信息
     * @return null|string
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * 设置错误信息
     * @param $code //错误代码
     * @param $msg  //错误说明
     */
    public function setError($code,$msg){
        $this->errorCode = $code;
        $this->error = $msg;
    }
}